# Generated by Django 3.2.13 on 2022-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=256)),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True, related_name="UserForms", to="forms.Form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserForms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=test_13_06_2022.db.models.deletion.CASCADE,
                        to="forms.form",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=test_13_06_2022.db.models.deletion.CASCADE,
                        to="forms.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=2048)),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True, related_name="answers", to="forms.Answer"
                    ),
                ),
                (
                    "right_answers",
                    models.ManyToManyField(
                        blank=True, related_name="right_answers", to="forms.Answer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="form",
            name="questions",
            field=models.ManyToManyField(blank=True, to="forms.Question"),
        ),
        migrations.AddField(
            model_name="form",
            name="user",
            field=models.ManyToManyField(
                blank=True, through="forms.UserForms", to="forms.User"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=test_13_06_2022.db.models.deletion.CASCADE, to="forms.user"
            ),
        ),
    ]
